FLASK_APP=app.py
FLASK_RUN_HOST=0.0.0.0
FLASK_RUN_PORT=5001
FLASK_DEBUG=True

OPENAI_MODEL=gpt-4o-mini
OPENAI_TEMPERATURE=0.7
OPENAI_MAX_TOKENS= 300
OPENAI_FREQUENCY_PENALTY=0
OPENAI_PRESENCE_PENALTY=0

SESSION_PERMANENT=False
SESSION_LIFETIME_HOURS=24
SESSION_COOKIE_SECURE=False
SESSION_COOKIE_HTTPONLY=True
SESSION_COOKIE_SAMESITE=Lax
SESSION_CLEANUP_INTERVAL_MINUTES=60

SYSTEM_PROMPT_FILE=system_prompt.txt